{"job_id": 59, "Status": "Error Traceback (most recent call last):\n  File \"/app/file_process/Resume_Scoring.py\", line 1427, in process_file\n    resp = main(org_file_list, job_folder, jd_input, experience, mandatory_skills, secondary_skills)\n  File \"/app/file_process/Resume_Scoring.py\", line 1117, in main\n    exp_df[['Total_Exp_With_Years','Total_Gaps_With_Years']] = pd.DataFrame(exp_df.Total_and_Gaps.tolist(), index= exp_df.index)\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/frame.py\", line 3966, in __setitem__\n    self._setitem_array(key, value)\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/frame.py\", line 4008, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/indexers/utils.py\", line 402, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n", "File": "", "Percent": 25, "Error_code": 1}